memcheck: 
	valgrind --leak-check=yes ./csim -s 4 -E 1 -b 4 -t ./traces/trace1 # or other test
	#valgrind --leak-check=yes ./test213 # or other test
	#valgrind --leak-check=yes ./test214_immedcoal # or other test


