FROM ubuntu:24.10
#RUN apt-get update && apt-get install -y python3 python3-pip curl iproute2
#COPY requirements.txt /tmp/requirements.txt
#RUN pip3 install -r /tmp/requirements.txt --break-system-packages
RUN apt-get update && apt-get install -y python3 pip curl iproute2
RUN python3 -m pip install grpcio-tools==1.70.0 grpcio==1.70.0 protobuf==5.29.3 pandas==2.2.2 flask --break-system-packages 
COPY cache.py ./cache.py
COPY PropertyLookup.proto ./PropertyLookup.proto
RUN python3 -m grpc_tools.protoc -I=. --python_out=. --grpc_python_out=. PropertyLookup.proto
#CMD ["python3", "-m", "cache", "--ip=0.0.0.0", "--port=8080"]
#CMD ["python3", "-m", "cache"]
CMD ["python3",  "cache.py"]