p1: # occurrances of the word Documentary in this file
	grep -P "Documentary" movies.csv
p2: # prices that end with the digit 9
	grep -P "^\d\d\d\d?9," cars.csv	
p3: # songs with two word titles
	grep -P "^[\w]+\s+[\w]+," songs.csv
p4: # ingredients with 1000 or more calories per 100 grams
	grep -P "\d\d\d\d cal" ingredients.csv 
p5: # meteorites with year 20XX where XX is any number
	grep -P "(d|l),20\d\d," meteorites.csv 
