# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lender_pb2 as lender__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lender_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DbToHdfs = channel.unary_unary(
                '/Lender/DbToHdfs',
                request_serializer=lender__pb2.Empty.SerializeToString,
                response_deserializer=lender__pb2.StatusString.FromString,
                _registered_method=True)
        self.BlockLocations = channel.unary_unary(
                '/Lender/BlockLocations',
                request_serializer=lender__pb2.BlockLocationsReq.SerializeToString,
                response_deserializer=lender__pb2.BlockLocationsResp.FromString,
                _registered_method=True)
        self.CalcAvgLoan = channel.unary_unary(
                '/Lender/CalcAvgLoan',
                request_serializer=lender__pb2.CalcAvgLoanReq.SerializeToString,
                response_deserializer=lender__pb2.CalcAvgLoanResp.FromString,
                _registered_method=True)


class LenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DbToHdfs(self, request, context):
        """Load input.data from SQL server and upload it to HDFS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockLocations(self, request, context):
        """Get the block locations of the Parquet file in HDFS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcAvgLoan(self, request, context):
        """Calculate the average loan amount for a given county_code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DbToHdfs': grpc.unary_unary_rpc_method_handler(
                    servicer.DbToHdfs,
                    request_deserializer=lender__pb2.Empty.FromString,
                    response_serializer=lender__pb2.StatusString.SerializeToString,
            ),
            'BlockLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockLocations,
                    request_deserializer=lender__pb2.BlockLocationsReq.FromString,
                    response_serializer=lender__pb2.BlockLocationsResp.SerializeToString,
            ),
            'CalcAvgLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcAvgLoan,
                    request_deserializer=lender__pb2.CalcAvgLoanReq.FromString,
                    response_serializer=lender__pb2.CalcAvgLoanResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Lender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Lender', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Lender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DbToHdfs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lender/DbToHdfs',
            lender__pb2.Empty.SerializeToString,
            lender__pb2.StatusString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lender/BlockLocations',
            lender__pb2.BlockLocationsReq.SerializeToString,
            lender__pb2.BlockLocationsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcAvgLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lender/CalcAvgLoan',
            lender__pb2.CalcAvgLoanReq.SerializeToString,
            lender__pb2.CalcAvgLoanResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
