# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lender.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clender.proto\"\x07\n\x05\x45mpty\"!\n\x11\x42lockLocationsReq\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x96\x01\n\x12\x42lockLocationsResp\x12<\n\rblock_entries\x18\x01 \x03(\x0b\x32%.BlockLocationsResp.BlockEntriesEntry\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x1a\x33\n\x11\x42lockEntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"%\n\x0e\x43\x61lcAvgLoanReq\x12\x13\n\x0b\x63ounty_code\x18\x01 \x01(\x05\"B\n\x0f\x43\x61lcAvgLoanResp\x12\x10\n\x08\x61vg_loan\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x1e\n\x0cStatusString\x12\x0e\n\x06status\x18\x01 \x01(\t2\x98\x01\n\x06Lender\x12!\n\x08\x44\x62ToHdfs\x12\x06.Empty\x1a\r.StatusString\x12\x39\n\x0e\x42lockLocations\x12\x12.BlockLocationsReq\x1a\x13.BlockLocationsResp\x12\x30\n\x0b\x43\x61lcAvgLoan\x12\x0f.CalcAvgLoanReq\x1a\x10.CalcAvgLoanRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKLOCATIONSRESP_BLOCKENTRIESENTRY']._loaded_options = None
  _globals['_BLOCKLOCATIONSRESP_BLOCKENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=16
  _globals['_EMPTY']._serialized_end=23
  _globals['_BLOCKLOCATIONSREQ']._serialized_start=25
  _globals['_BLOCKLOCATIONSREQ']._serialized_end=58
  _globals['_BLOCKLOCATIONSRESP']._serialized_start=61
  _globals['_BLOCKLOCATIONSRESP']._serialized_end=211
  _globals['_BLOCKLOCATIONSRESP_BLOCKENTRIESENTRY']._serialized_start=160
  _globals['_BLOCKLOCATIONSRESP_BLOCKENTRIESENTRY']._serialized_end=211
  _globals['_CALCAVGLOANREQ']._serialized_start=213
  _globals['_CALCAVGLOANREQ']._serialized_end=250
  _globals['_CALCAVGLOANRESP']._serialized_start=252
  _globals['_CALCAVGLOANRESP']._serialized_end=318
  _globals['_STATUSSTRING']._serialized_start=320
  _globals['_STATUSSTRING']._serialized_end=350
  _globals['_LENDER']._serialized_start=353
  _globals['_LENDER']._serialized_end=505
# @@protoc_insertion_point(module_scope)
